// This file was autogenerated by https://github.com/NeVeSpl/NTypewriter



export class TestItemDTO
{
    testItemId: number;
    questionId: number;

    //eslint-disable-next-line
    constructor()
    {
    
        this.testItemId = 0;
        this.questionId = 0;
    }
}