// This file was autogenerated by https://github.com/NeVeSpl/NTypewriter



export class TestDTO
{
    testId: number;
    title: string;

    //eslint-disable-next-line
    constructor()
    {
    
        this.testId = 0;
        this.title = "";
    }
}