// This file was autogenerated by https://github.com/NeVeSpl/NTypewriter

import { CreateAnswerDTO } from "../dtos/TestMe.Presentation.API.Controllers.Questions.Input.CreateAnswerDTO";

export class UpdateAnswerDTO extends CreateAnswerDTO
{
    answerId: number;

    //eslint-disable-next-line
    constructor()
    {
        super();
        this.answerId = 0;
    }
}