// This file was autogenerated by https://github.com/NeVeSpl/NTypewriter



export class CreateUserDTO
{
    name: string;
    emailAddress: string;
    password: string;

    //eslint-disable-next-line
    constructor()
    {
    
        this.name = "";
        this.emailAddress = "";
        this.password = "";
    }
}