// This file was autogenerated by https://github.com/NeVeSpl/NTypewriter



export class UpdateCatalogDTO
{
    name: string;

    //eslint-disable-next-line
    constructor()
    {
    
        this.name = "";
    }
}