// This file was autogenerated by https://github.com/NeVeSpl/NTypewriter



export class CatalogOnListDTO
{
    catalogId: number;
    name: string;

    //eslint-disable-next-line
    constructor()
    {
    
        this.catalogId = 0;
        this.name = "";
    }
}