// This file was autogenerated by https://github.com/NeVeSpl/NTypewriter



export class CreateCatalogDTO
{
    name: string;
    ownerId: number;

    //eslint-disable-next-line
    constructor()
    {
    
        this.name = "";
        this.ownerId = 0;
    }
}