// This file was autogenerated by https://github.com/NeVeSpl/NTypewriter



export class LoginCredentialsDTO
{
    email: string;
    password: string;

    //eslint-disable-next-line
    constructor()
    {
    
        this.email = "";
        this.password = "";
    }
}