// This file was autogenerated by https://github.com/NeVeSpl/NTypewriter



export class CreateTestItemDTO
{
    questionId: number;

    //eslint-disable-next-line
    constructor()
    {
    
        this.questionId = 0;
    }
}