// This file was autogenerated by https://github.com/NeVeSpl/NTypewriter



export class AnswerDTO
{
    answerId: number;
    content: string;
    isCorrect: boolean;

    //eslint-disable-next-line
    constructor()
    {
    
        this.answerId = 0;
        this.content = "";
        this.isCorrect = false;
    }
}