// This file was autogenerated by https://github.com/NeVeSpl/NTypewriter



export class CreateTestDTO
{
    title: string;
    ownerId: number;

    //eslint-disable-next-line
    constructor()
    {
    
        this.title = "";
        this.ownerId = 0;
    }
}