// This file was autogenerated by https://github.com/NeVeSpl/NTypewriter



export class QuestionOnListDTO
{
    questionId: number;
    content: string;
    concurrencyToken: number;

    //eslint-disable-next-line
    constructor()
    {
    
        this.questionId = 0;
        this.content = "";
        this.concurrencyToken = 0;
    }
}