// This file was autogenerated by https://github.com/NeVeSpl/NTypewriter

import { CreateTestItemDTO } from "../dtos/TestMe.Presentation.API.Controllers.Tests.Input.CreateTestItemDTO";

export class UpdateTestItemDTO extends CreateTestItemDTO
{

    //eslint-disable-next-line
    constructor()
    {
        super();
    }
}