// This file was autogenerated by https://github.com/NeVeSpl/NTypewriter



export class UpdateTestDTO
{
    title: string;

    //eslint-disable-next-line
    constructor()
    {
    
        this.title = "";
    }
}