// This file was autogenerated by https://github.com/NeVeSpl/NTypewriter

import { UserRole } from "../enums/TestMe.UserManagement.Domain.UserRole";

export class UserCredentialsDTO
{
    id: number;
    userRole: UserRole;

    //eslint-disable-next-line
    constructor()
    {
    
        this.id = 0;
        this.userRole = 0;
    }
}