// This file was autogenerated by https://github.com/NeVeSpl/NTypewriter



export class TokenDTO
{
    token: string;

    //eslint-disable-next-line
    constructor()
    {
    
        this.token = "";
    }
}