// This file was autogenerated by https://github.com/NeVeSpl/NTypewriter



export class CatalogDTO
{
    catalogId: number;
    name: string;
    questionsCount: number;

    //eslint-disable-next-line
    constructor()
    {
    
        this.catalogId = 0;
        this.name = "";
        this.questionsCount = 0;
    }
}