// This file was autogenerated by https://github.com/NeVeSpl/NTypewriter

import { UserRole } from "../enums/TestMe.UserManagement.Domain.UserRole";
import { MembershipLevel } from "../enums/TestMe.SharedKernel.Domain.MembershipLevel";

export class UserDTO
{
    userId: number;
    name: string | null;
    emailAddress: string;
    role: UserRole;
    membershipLevel: MembershipLevel;

    //eslint-disable-next-line
    constructor()
    {
    
        this.userId = 0;
        this.name = null;
        this.emailAddress = "";
        this.role = 0;
        this.membershipLevel = 0;
    }
}