// This file was autogenerated by https://github.com/NeVeSpl/NTypewriter



export class CreateAnswerDTO
{
    content: string;
    isCorrect: boolean;

    //eslint-disable-next-line
    constructor()
    {
    
        this.content = "";
        this.isCorrect = false;
    }
}