// This file was autogenerated by http://frhagn.github.io/Typewriter/

import { CatalogDTO } from "../dtos/TestMe.TestCreation.App.TestsCatalogs.Output.CatalogDTO";

export class TestsCatalogDTO extends CatalogDTO
{ 

    constructor()
    {  
         super();   
    }
}