// This file was autogenerated by http://frhagn.github.io/Typewriter/



export class CreateQuestionItemDTO 
{ 
    questionId: number;

    //eslint-disable-next-line
    constructor()
    {  
            
         this.questionId = 0;
    }
}