// This file was autogenerated by http://frhagn.github.io/Typewriter/

import { AnswerDTO } from "../dtos/TestMe.TestCreation.App.Questions.Output.AnswerDTO";
import { QuestionHeaderDTO } from "../dtos/TestMe.TestCreation.App.Questions.Output.QuestionHeaderDTO";

export class QuestionDTO extends QuestionHeaderDTO
{ 
    answers: AnswerDTO[];
    concurrencyToken: number;

    constructor()
    {  
         super();   
         this.answers = [];
         this.concurrencyToken = 0;
    }
}