// This file was autogenerated by http://frhagn.github.io/Typewriter/



export class UpdateTestDTO 
{ 
    title: string;

    //eslint-disable-next-line
    constructor()
    {  
            
         this.title = "";
    }
}