// This file was autogenerated by http://frhagn.github.io/Typewriter/



export class QuestionHeaderDTO 
{ 
    questionId: number;
    content: string;
    catalogId: number;

    constructor()
    {  
            
         this.questionId = 0;
         this.content = "";
         this.catalogId = 0;
    }
}