// This file was autogenerated by http://frhagn.github.io/Typewriter/



export class CatalogHeaderDTO 
{ 
    catalogId: number;
    name: string;

    //eslint-disable-next-line
    constructor()
    {  
            
         this.catalogId = 0;
         this.name = "";
    }
}