// This file was autogenerated by http://frhagn.github.io/Typewriter/



export class CreateCatalogDTO
{
    name: string;
    ownerId: number;

    //eslint-disable-next-line
    constructor()
    {
    
        this.name = "";
        this.ownerId = 0;
    }
}