// This file was autogenerated by http://frhagn.github.io/Typewriter/

import { CatalogHeaderDTO } from "../dtos/TestMe.TestCreation.App.TestsCatalogs.Output.CatalogHeaderDTO";

export class CatalogDTO extends CatalogHeaderDTO
{ 

    //eslint-disable-next-line
    constructor()
    {  
         super();   
    }
}