// This file was autogenerated by http://frhagn.github.io/Typewriter/

import { CreateTestDTO } from "../dtos/TestMe.Presentation.API.Controllers.Tests.Input.CreateTestDTO";

export class UpdateTestDTO extends CreateTestDTO
{ 

    constructor()
    {  
         super();   
    }
}