// This file was autogenerated by http://frhagn.github.io/Typewriter/



export class TokenDTO 
{ 
    token: string;

    //eslint-disable-next-line
    constructor()
    {  
            
         this.token = "";
    }
}