// This file was autogenerated by http://frhagn.github.io/Typewriter/



export class LoginCredentialsDTO 
{ 
    email: string;
    password: string;

    //eslint-disable-next-line
    constructor()
    {  
            
         this.email = "";
         this.password = "";
    }
}