// This file was autogenerated by http://frhagn.github.io/Typewriter/

import { UserRole } from "../enums/TestMe.UserManagement.Domain.UserRole";
import { MembershipLevel } from "../enums/TestMe.SharedKernel.Domain.MembershipLevel";

export class UserDTO 
{ 
    userId: number;
    name: string;
    emailAddress: string;
    role: UserRole;
    membershipLevel: MembershipLevel;

    constructor()
    {  
            
         this.userId = 0;
         this.name = "";
         this.emailAddress = "";
         this.role = 0;
         this.membershipLevel = 0;
    }
}