// This file was autogenerated by http://frhagn.github.io/Typewriter/



export class TestItemDTO
{
    testItemId: number;
    questionId: number;

    //eslint-disable-next-line
    constructor()
    {
    
        this.testItemId = 0;
        this.questionId = 0;
    }
}