// This file was autogenerated by http://frhagn.github.io/Typewriter/



export class AnswerDTO 
{ 
    answerId: number;
    content: string;
    isCorrect: boolean;

    constructor()
    {  
            
         this.answerId = 0;
         this.content = "";
         this.isCorrect = false;
    }
}