// This file was autogenerated by http://frhagn.github.io/Typewriter/



export class TestHeaderDTO 
{ 
    testId: number;
    title: string;

    constructor()
    {  
            
         this.testId = 0;
         this.title = "";
    }
}