// This file was autogenerated by http://frhagn.github.io/Typewriter/



export class QuestionOnListDTO 
{ 
    questionId: number;
    content: string;
    concurrencyToken: number;

    //eslint-disable-next-line
    constructor()
    {  
            
         this.questionId = 0;
         this.content = "";
         this.concurrencyToken = 0;
    }
}