// This file was autogenerated by http://frhagn.github.io/Typewriter/

import { CreateQuestionItemDTO } from "../dtos/TestMe.Presentation.API.Controllers.Tests.Input.CreateQuestionItemDTO";

export class UpdateQuestionItemDTO extends CreateQuestionItemDTO
{ 

    //eslint-disable-next-line
    constructor()
    {  
         super();   
    }
}