// This file was autogenerated by http://frhagn.github.io/Typewriter/



export class CreateUserDTO 
{ 
    name: string;
    emailAddress: string;
    password: string;

    //eslint-disable-next-line
    constructor()
    {  
            
         this.name = "";
         this.emailAddress = "";
         this.password = "";
    }
}