// This file was autogenerated by http://frhagn.github.io/Typewriter/

import { QuestionHeaderDTO } from "../dtos/TestMe.TestCreation.App.Tests.Output.QuestionHeaderDTO";

export class QuestionItemDTO 
{ 
    question: QuestionHeaderDTO;

    constructor()
    {  
            
         this.question = {} as QuestionHeaderDTO;
    }
}