// This file was autogenerated by http://frhagn.github.io/Typewriter/



export class CreateTestDTO 
{ 
    catalogId: number;
    title: string;

    constructor()
    {  
            
         this.catalogId = 0;
         this.title = "";
    }
}