// This file was autogenerated by http://frhagn.github.io/Typewriter/

import { CatalogDTO } from "../dtos/TestMe.TestCreation.App.QuestionsCatalogs.Output.CatalogDTO";

export class QuestionsCatalogDTO extends CatalogDTO
{ 
    questionsCount: number;

    constructor()
    {  
         super();   
         this.questionsCount = 0;
    }
}