// This file was autogenerated by http://frhagn.github.io/Typewriter/



export class CreateTestDTO 
{ 
    title: string;
    ownerId: number;

    //eslint-disable-next-line
    constructor()
    {  
            
         this.title = "";
         this.ownerId = 0;
    }
}