// This file was autogenerated by http://frhagn.github.io/Typewriter/



export class TestDTO 
{ 
    testId: number;
    title: string;

    //eslint-disable-next-line
    constructor()
    {  
            
         this.testId = 0;
         this.title = "";
    }
}