// This file was autogenerated by http://frhagn.github.io/Typewriter/



export class QuestionHeaderDTO 
{ 
    questionId: number;
    content: string;

    //eslint-disable-next-line
    constructor()
    {  
            
         this.questionId = 0;
         this.content = "";
    }
}