// This file was autogenerated by http://frhagn.github.io/Typewriter/



export class CreateCatalogDTO 
{ 
    name: string;

    //eslint-disable-next-line
    constructor()
    {  
            
         this.name = "";
    }
}