// This file was autogenerated by http://frhagn.github.io/Typewriter/

import { CreateAnswerDTO } from "../dtos/TestMe.Presentation.API.Controllers.Questions.Input.CreateAnswerDTO";

export class UpdateAnswerDTO extends CreateAnswerDTO
{ 
    answerId: number;

    constructor()
    {  
         super();   
         this.answerId = 0;
    }
}