// This file was autogenerated by http://frhagn.github.io/Typewriter/



export class CreateAnswerDTO 
{ 
    content: string;
    isCorrect: boolean;

    constructor()
    {  
            
         this.content = "";
         this.isCorrect = false;
    }
}