// This file was autogenerated by http://frhagn.github.io/Typewriter/

import { UserRole } from "../enums/TestMe.UserManagement.Domain.UserRole";

export class UserCredentialsDTO 
{ 
    id: number;
    userRole: UserRole;

    //eslint-disable-next-line
    constructor()
    {  
            
         this.id = 0;
         this.userRole = 0;
    }
}