// This file was autogenerated by http://frhagn.github.io/Typewriter/

import { CreateCatalogDTO } from "../dtos/TestMe.Presentation.API.Controllers.QuestionsCatalogs.Input.CreateCatalogDTO";

export class UpdateCatalogDTO extends CreateCatalogDTO
{ 

    constructor()
    {  
         super();   
    }
}