// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TestMe.TestCreation.Persistence;

namespace TestMe.TestCreation.Migrations
{
    [DbContext(typeof(TestCreationDbContext))]
    partial class TestCreationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("TestCreation")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("TestMe.BuildingBlocks.EventBus.Event", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("PostDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ReceivedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RoutingKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EventId");

                    b.ToTable("Inbox");
                });

            modelBuilder.Entity("TestMe.TestCreation.Domain.Catalog", b =>
                {
                    b.Property<long>("CatalogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying(2048)")
                        .HasMaxLength(2048);

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint");

                    b.HasKey("CatalogId");

                    b.HasIndex("CatalogId");

                    b.ToTable("Catalog");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Catalog");
                });

            modelBuilder.Entity("TestMe.TestCreation.Domain.Owner", b =>
                {
                    b.Property<long>("OwnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("MembershipLevel")
                        .HasColumnType("integer");

                    b.Property<int>("QuestionsCatalogsCount")
                        .HasColumnType("integer");

                    b.HasKey("OwnerId");

                    b.ToTable("Owners");
                });

            modelBuilder.Entity("TestMe.TestCreation.Domain.Question", b =>
                {
                    b.Property<long>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("CatalogId")
                        .HasColumnType("bigint");

                    b.Property<uint>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnName("xmin")
                        .HasColumnType("xid")
                        .HasDefaultValue(0u);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("character varying(2048)")
                        .HasMaxLength(2048);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint");

                    b.HasKey("QuestionId");

                    b.HasIndex("CatalogId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("TestMe.TestCreation.Domain.QuestionsCatalogItem", b =>
                {
                    b.Property<long>("CatalogOfQuestionsItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("CatalogOfQuestionsCatalogId")
                        .HasColumnType("bigint");

                    b.Property<long>("TestId")
                        .HasColumnType("bigint");

                    b.HasKey("CatalogOfQuestionsItemId");

                    b.HasIndex("CatalogOfQuestionsCatalogId");

                    b.ToTable("QuestionsCatalogItem");
                });

            modelBuilder.Entity("TestMe.TestCreation.Domain.Test", b =>
                {
                    b.Property<long>("TestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("CatalogId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("character varying(2048)")
                        .HasMaxLength(2048);

                    b.HasKey("TestId");

                    b.HasIndex("CatalogId");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("TestMe.TestCreation.Domain.QuestionsCatalog", b =>
                {
                    b.HasBaseType("TestMe.TestCreation.Domain.Catalog");

                    b.Property<int>("QuestionsCount")
                        .HasColumnType("integer");

                    b.HasIndex("OwnerId");

                    b.HasDiscriminator().HasValue("QuestionsCatalog");
                });

            modelBuilder.Entity("TestMe.TestCreation.Domain.TestsCatalog", b =>
                {
                    b.HasBaseType("TestMe.TestCreation.Domain.Catalog");

                    b.HasIndex("OwnerId")
                        .HasName("IX_Catalog_OwnerId1");

                    b.HasDiscriminator().HasValue("TestsCatalog");
                });

            modelBuilder.Entity("TestMe.TestCreation.Domain.Question", b =>
                {
                    b.HasOne("TestMe.TestCreation.Domain.QuestionsCatalog", null)
                        .WithMany("Questions")
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("TestMe.TestCreation.Domain.Answer", "Answers", b1 =>
                        {
                            b1.Property<long>("AnswerId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                            b1.Property<string>("Content")
                                .IsRequired()
                                .HasColumnType("character varying(2048)")
                                .HasMaxLength(2048);

                            b1.Property<bool>("IsCorrect")
                                .HasColumnType("boolean");

                            b1.Property<short>("OrdinalNumber")
                                .HasColumnType("smallint");

                            b1.Property<long>("QuestionId")
                                .HasColumnType("bigint");

                            b1.HasKey("AnswerId");

                            b1.HasIndex("QuestionId");

                            b1.ToTable("Answer");

                            b1.WithOwner()
                                .HasForeignKey("QuestionId");
                        });
                });

            modelBuilder.Entity("TestMe.TestCreation.Domain.QuestionsCatalogItem", b =>
                {
                    b.HasOne("TestMe.TestCreation.Domain.QuestionsCatalog", "CatalogOfQuestions")
                        .WithMany()
                        .HasForeignKey("CatalogOfQuestionsCatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TestMe.TestCreation.Domain.Test", b =>
                {
                    b.HasOne("TestMe.TestCreation.Domain.TestsCatalog", null)
                        .WithMany("Tests")
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("TestMe.TestCreation.Domain.QuestionItem", "Questions", b1 =>
                        {
                            b1.Property<long>("QuestionItemId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                            b1.Property<long>("QuestionId")
                                .HasColumnType("bigint");

                            b1.Property<long>("TestId")
                                .HasColumnType("bigint");

                            b1.HasKey("QuestionItemId");

                            b1.HasIndex("QuestionId");

                            b1.HasIndex("QuestionItemId");

                            b1.HasIndex("TestId");

                            b1.ToTable("QuestionItem");

                            b1.HasOne("TestMe.TestCreation.Domain.Question", "Question")
                                .WithMany()
                                .HasForeignKey("QuestionId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("TestId");
                        });
                });

            modelBuilder.Entity("TestMe.TestCreation.Domain.QuestionsCatalog", b =>
                {
                    b.HasOne("TestMe.TestCreation.Domain.Owner", null)
                        .WithMany("QuestionsCatalogs")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TestMe.TestCreation.Domain.TestsCatalog", b =>
                {
                    b.HasOne("TestMe.TestCreation.Domain.Owner", null)
                        .WithMany("TestsCatalogs")
                        .HasForeignKey("OwnerId")
                        .HasConstraintName("FK_Catalog_Owners_OwnerId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
