// This file was autogenerated by https://github.com/NeVeSpl/NTypewriter


//eslint-disable-next-line
import { ApiBaseService, IUseRequest, IUseRequestWithResult, useRequest, useRequestWithResult, CursorPagedResults, CursorPagination, OffsetPagedResults, OffsetPagination } from "../base/index";
import { TokenDTO } from "../dtos/TestMe.Presentation.API.Controllers.Tokens.Output.TokenDTO";
import { LoginCredentialsDTO } from "../dtos/TestMe.Presentation.API.Controllers.Tokens.Input.LoginCredentialsDTO";
export * from "../dtos/TestMe.Presentation.API.Controllers.Tokens.Output.TokenDTO";
export * from "../dtos/TestMe.Presentation.API.Controllers.Tokens.Input.LoginCredentialsDTO";
export * from "../base/index";

export class TokensService extends ApiBaseService
{
    static Type = "TokensService";

    createToken(loginCredentials: LoginCredentialsDTO) : Promise<TokenDTO>
    {
        return this.MakeRequestWithResult<TokenDTO>("post", `Tokens`, loginCredentials);
    }
    createTokenAsync(loginCredentials: LoginCredentialsDTO) : Promise<TokenDTO>
    {
        return this.MakeRequestWithResult<TokenDTO>("post", `Tokens/Async`, loginCredentials);
    }
    
}


