// This file was autogenerated by http://frhagn.github.io/Typewriter/


import { ApiBaseService } from "../base/index";
//eslint-disable-next-line 
 import { OffsetPagedResults } from "../base/OffsetPagedResults";
//eslint-disable-next-line 
 import { CatalogHeaderDTO } from "../dtos/TestMe.TestCreation.App.QuestionsCatalogs.Output.CatalogHeaderDTO";
//eslint-disable-next-line 
 import { OffsetPagination } from "../base/OffsetPagination";
//eslint-disable-next-line 
 import { QuestionsCatalogDTO } from "../dtos/TestMe.TestCreation.App.QuestionsCatalogs.Output.QuestionsCatalogDTO";
//eslint-disable-next-line 
 import { CatalogDTO } from "../dtos/TestMe.TestCreation.App.QuestionsCatalogs.Output.CatalogDTO";
//eslint-disable-next-line 
 import { CreateCatalogDTO } from "../dtos/TestMe.Presentation.API.Controllers.QuestionsCatalogs.Input.CreateCatalogDTO";
//eslint-disable-next-line 
 import { UpdateCatalogDTO } from "../dtos/TestMe.Presentation.API.Controllers.QuestionsCatalogs.Input.UpdateCatalogDTO";
export * from "../base/OffsetPagedResults";
export * from "../dtos/TestMe.TestCreation.App.QuestionsCatalogs.Output.CatalogHeaderDTO";
export * from "../base/OffsetPagination";
export * from "../dtos/TestMe.TestCreation.App.QuestionsCatalogs.Output.QuestionsCatalogDTO";
export * from "../dtos/TestMe.TestCreation.App.QuestionsCatalogs.Output.CatalogDTO";
export * from "../dtos/TestMe.Presentation.API.Controllers.QuestionsCatalogs.Input.CreateCatalogDTO";
export * from "../dtos/TestMe.Presentation.API.Controllers.QuestionsCatalogs.Input.UpdateCatalogDTO";
export * from "../base/index";

export class QuestionsCatalogsService extends ApiBaseService
{
    readQuestionsCatalogHeaders(ownerId: number, pagination: OffsetPagination) : Promise<OffsetPagedResults<CatalogHeaderDTO>>
    {
        return this.MakeRequest<OffsetPagedResults<CatalogHeaderDTO>>("get", `QuestionsCatalogs/headers?ownerId=${ownerId}&offset=${pagination.offset}&limit=${pagination.limit}`, null);
    }
    readQuestionsCatalogHeader(catalogId: number) : Promise<CatalogHeaderDTO>
    {
        return this.MakeRequest<CatalogHeaderDTO>("get", `QuestionsCatalogs/${catalogId}/header`, null);
    }
    readQuestionsCatalog(catalogId: number) : Promise<QuestionsCatalogDTO>
    {
        return this.MakeRequest<QuestionsCatalogDTO>("get", `QuestionsCatalogs/${catalogId}`, null);
    }
    createCatalog(createCatalog: CreateCatalogDTO) : Promise<number>
    {
        return this.MakeRequest<number>("post", `QuestionsCatalogs`, createCatalog);
    }
    updateCatalog(catalogId: number, updateCatalog: UpdateCatalogDTO) 
    {
        return this.MakeRequest("put", `QuestionsCatalogs/${catalogId}`, updateCatalog);
    }
    deleteCatalog(catalogId: number) 
    {
        return this.MakeRequest("delete", `QuestionsCatalogs/${catalogId}`, null);
    }
           
}