// This file was autogenerated by http://frhagn.github.io/Typewriter/


import { ApiBaseService } from "../base/index";
//eslint-disable-next-line 
 import { TokenDTO } from "../dtos/TestMe.Presentation.API.Controllers.Tokens.Output.TokenDTO";
//eslint-disable-next-line 
 import { LoginCredentialsDTO } from "../dtos/TestMe.Presentation.API.Controllers.Tokens.Input.LoginCredentialsDTO";
export * from "../dtos/TestMe.Presentation.API.Controllers.Tokens.Output.TokenDTO";
export * from "../dtos/TestMe.Presentation.API.Controllers.Tokens.Input.LoginCredentialsDTO";
export * from "../base/index";

export class TokensService extends ApiBaseService
{
    createToken(loginCredentials: LoginCredentialsDTO) : Promise<TokenDTO>
    {
        return this.MakeRequest<TokenDTO>("post", `Tokens`, loginCredentials);
    }
    createTokenAsync(loginCredentials: LoginCredentialsDTO) : Promise<TokenDTO>
    {
        return this.MakeRequest<TokenDTO>("post", `Tokens/Async`, loginCredentials);
    }
           
}