// This file was autogenerated by http://frhagn.github.io/Typewriter/


import { ApiBaseService } from "../base/index";
import { CreateUserDTO } from "../dtos/TestMe.Presentation.API.Controllers.Users.Input.CreateUserDTO";
import { CursorPagedResults } from "../base/CursorPagedResults";
import { UserDTO } from "../dtos/TestMe.UserManagement.App.Users.Output.UserDTO";
import { CursorPagination } from "../base/CursorPagination";
export * from "../dtos/TestMe.Presentation.API.Controllers.Users.Input.CreateUserDTO";
export * from "../base/CursorPagedResults";
export * from "../dtos/TestMe.UserManagement.App.Users.Output.UserDTO";
export * from "../base/CursorPagination";
export * from "../base/index";

export class UsersService extends ApiBaseService
{
    createUser(createUser: CreateUserDTO) : Promise<number>
    {
        return this.MakeRequest<number>("post", `Users`, createUser);
    }
    readUsers(pagination: CursorPagination) : Promise<CursorPagedResults<UserDTO>>
    {
        return this.MakeRequest<CursorPagedResults<UserDTO>>("get", `Users?cursor=${pagination.cursor}&fetchNext=${pagination.fetchNext}`, null);
    }
    isEmailAddressTaken(emailAddress: string) : Promise<boolean>
    {
        return this.MakeRequest<boolean>("get", `Users/EmailAddress/IsTaken?emailAddress=${encodeURIComponent(emailAddress)}`, null);
    }
           
}